title: Snakes that I never knew before
author: HannahF44
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog shows snakes that I've never heard of before and my opinon on them.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
