title: Snakes that I never heard of before
author: Hannah Fannon
email: hannnfannon@students.k12k.com
description: > # this means to ignore newlines until "baseurl:"
  This blog shows snakes I've never heard of before and my opinion about them.

# social links
github_username:  HannahF44 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
